# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QAbstractItemView


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundImage = QtWidgets.QLabel(self.centralwidget)
        self.backgroundImage.setText("")
        pixmap = QtGui.QPixmap("../images/dixit-cover.jpg")
        self.backgroundImage.resize(pixmap.width(), pixmap.height())
        self.backgroundImage.setPixmap(pixmap)
        self.resize(self.backgroundImage.width(), self.backgroundImage.height())
        self.backgroundImage.setObjectName("backgroundImage")
        self.onlineUsers = QtWidgets.QTableWidget(0, 2, self.centralwidget)
        self.onlineUsers.setGeometry(QtCore.QRect(850, 450, 300, 200))
        self.onlineUsers.setSelectionMode(QAbstractItemView.NoSelection)
        self.onlineUsers.setStyleSheet("QTableWidget {background-color: transparent;}"
            "QTableWidget {border: 0;}"
            "QHeaderView::section {background-color: transparent;}"
            "QHeaderView {background-color: transparent;}"
            "QTableCornerButton::section {background-color: transparent;}")
        self.onlineUsers.setShowGrid(False)
        self.onlineUsers.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.onlineUsers.setObjectName("onlineUsers")
        self.onlineUsers.setWindowTitle("online users")
        self.onlineUsers.setHorizontalHeaderLabels(('Name', 'IP'))
        self.readyBox = QtWidgets.QCheckBox(self.centralwidget)
        self.readyBox.setGeometry(QtCore.QRect(530, 460, 121, 20))
        self.readyBox.setObjectName("readyBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.readyBox.setText(_translate("MainWindow", "I AM READY"))
